### ISSUE TITLE
Tests are inside out

### ISSUE THREAD

**Issue by erikrose** [erikrose/blessings#109]
The test setup on the blessed-integration branch is unconventional. At the moment, `setup.py develop` is overridden to install test dependencies (where a typical project will simply fill out the `tests_require` setup() kwarg), and `setup.py test` is overridden to run tox (where a typical project will just run the tests using the current version of Python). It's then usual to have tox run explicitly from the Travis config to do multi-version testing. Is there a compelling motivation to do things differently?

**Comment by jquast** [comment]
It's a convention i've been using for a while, but not a community convention.  The idea is, that if you're going to "develop" a package, you should have the tools necessary to test it.  Without such convention, it is necessary to have a "requirements-testing.txt" and documentation that explicitly states, "To test, first, prepare your environment in this way ..."

> It's then usual to have tox run explicitly from the Travis config to do multi-version testing.

This absolutely is a convention, it is a suggestion solution by the community so that "tox" locally executes in the same manner as travis-ci does.

https://github.com/pyca/cryptography/blob/master/.travis.yml
https://www.dominicrodger.com/tox-and-travis.html
http://jsatt.com/blog/using-tox-with-travis-ci-to-test-django-apps/
https://github.com/pyca/pyopenssl/blob/master/.travis.yml

**Comment by erikrose** [comment]
>  The idea is, that if you're going to "develop" a package, you should have the tools necessary to test it.

Typically, running `python setup.py test` takes care of installing test dependencies, care of setuptools' built-in `tests_require`. Then you don't need to write your own distutils Command subclass.
