### ISSUE TITLE
Python 2 blows up despite not testing types (badly or otherwise)

### ISSUE THREAD

**Issue by cwillu** [erikrose/blessings#120]
> Everything that comes out of the library is now unicode. This lets us support Python 3 without making a mess of the code, and Python 2 should continue to work unless you were testing types (and badly). Please file a bug if this causes trouble for you.

Except that's not how it works, if you have a byte string that already contains utf-8:

> > > properly_encoded_utf8_from_elsewhere = u'\u2026'.encode('utf-8')
> > > blessings.Terminal().clear_eol + properly_encoded_utf8_from_elsewhere
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

So now I get to liberally sprinkle .encode('utf-8')'s on all my cursed blessings to make it work right.

**Comment by jquast** [comment]
@cwillu I'm afraid this cannot be resolved in the blessings library, you really do need to "sprinkle" as you wish not to do. The basic premise: you should always use unicode strings in your code, and only encode to utf8 bytes at the "edge". For example, write your own `input()` functions to read utf8 bytes into unicode, and an `echo()` function that writes unicode strings to utf8 bytes, your "edges" (input and output) now handle this complication in just two small places, and the rest of your code uses unicode everywhere.

The reason this happens is because by concatenating a unicode string and bytestring together, python must "upconvert" one of the data types to the other. So, in your case, it tries to covert the first byte of `…`, represented as utf8 bytes, `\xe2\x80\xa6`, with a unicode string. So the bytes must be *coerced* to unicode, implicitly, without your direction.

Because python doesn't know what encoding it is, it implicitly assumes ascii. And because this is not in range of ascii, you see the error given. It could be any encoding, like ISO-2022-JP on a japanese computer. Python just choses the most common and basic encoding, ascii.

I know this is difficult, and I'm sorry, and if you really want a quick fix without sprinkling .decode()'s and .encodes(), and you don't care about unicode vs. ascii vs. utf8, and you're probably just writing code for fun and not serious production systems used by many international folk, you can change this implicitly coerced `ascii` codec to 'utf8' so everything appears to work without problems, and without "sprinkling" using the `sys.setdefaultencoding()` function, for example discussed on stack overflow here: https://stackoverflow.com/a/3828742

You assume utf8 everywhere, but have you met a russian who uses koi8? this person may wish to select a different encoding than utf8...

---

So in conclusion, blessings cannot help you here, or make any change to make this "just work" -- it is the python language itself that performs this implicit conversion when faced with your `u"nicode" + b"ytes"` problem. blessings cannot know that its output will be mixed with bytes or accomodate it, as a dynamic language it is not aware of the context that it is used (we cannot know our function's output will have a `+` on either side of it).

This is why blessings makes the very kind compromise of emitting unicode -- the most pythonic and friendly thing to do. If it were to emit utf8 bytes, many many folks would be very unhappy to work with the api, you are arguing for a minority of folks who are frankly architecting code the wrong way :(

I hope this is helpful and you are not too frustrated. Remember to have fun and that learning how to write quality code by playing with experiments is a valuable and free lesson, and should be much funner than university computer science or a dayjob :)
