### ISSUE TITLE
automatically color all input (or output)? 

### ISSUE THREAD

**Issue by landroni** [erikrose/blessings#122]
Can `blessings` be used to automatically color all input (or output) in the Python console? I would like to make the console input/output be more userfriendly and readable (using a terminal on Linux). 

Thanks

**Comment by jquast** [comment]
No.

If you wish to write this program, it will need to use a pty (pseudo terminal). I would recommend using a pty, so that your program can "capture" both input and output, maybe around this library https://pypi.python.org/pypi/ptyprocess or a custom version of variant of the "interactive" method of pexpect, https://github.com/pexpect/pexpect/blob/b36c03315fcf9bec711f79098b2fa31dfd264c76/pexpect/pty_spawn.py#L697 (which uses the ptyprocess module)
