### ISSUE TITLE
Won't support watch --color

### ISSUE THREAD

**Issue by Stonesjtu** [erikrose/blessings#123]
It's better to set to the colored mode (don't know the exact name) when the `watch` is running with `--color` option.

**Comment by erikrose** [comment]
Sorry, what's `watch`? Are you sure you're in the right place?

**Comment by erikrose** [comment]
From watch's man page, I don't see that it gives any hints (via setting env vars or passing args to the called process) as to whether color is enabled, so, unfortunately, blessings has no nice way of telling. I suppose blessings could call `ps` or something and try to guess what its parent process and the args thereof were, but that's proably not very reliable, messy, and limited to UNIX-like OSes.

**Comment by jquast** [comment]
Dearest @Stonesjtu, this is precisely what the `foce_styling=True` argument to blessings.Terminal() was designed to support, and blessings supports this use case fine. http://blessings.readthedocs.io/en/latest/#blessings.Terminal.__init__

ls(1) would have this same problem, and must be forced -- `watch --color 'ls -FG'` does not work on my mac with gnu watch 3.3.12 installed, however, from manual of ls(1) for mac, `CLICOLOR_FORCE=1 watch --color 'ls -FG'` causes color output to work, for the very same reason of blessings, that color is not used when not connected to a terminal.

example:

```
watch --color 'TERM=ansi python -c "import blessings;print(blessings.Terminal(force_styling=True).blue(\"smurf\"))"'
```

note that this "color interpretation" by watch is very poor and may not support most of the sequences that blessings can generate, and depends on a number of things about your system and current `TERM` type, here we set `TERM=ansi` to help stay within watch(1)'s strict ansi decoder, which can be seen here: https://gitlab.com/procps-ng/procps/blob/4e2a1ba9b194f359471f80bd4d00e591ba740ce4/watch.c#L141

When color is necessary, I often just do:
```
while [ 0 ]; do ./XXX.py; sleep 1; clear; done
```

(The only good use for watch(1) instead of simple shell script is when the `-d` diff argument is needed, perhaps. this is the only feature watch(1) offers that cannot be rapidly scripted in any shell!)
