### ISSUE TITLE
Releases are on PyPI but not here on GitHub; active branch is hidden

### ISSUE THREAD

**Issue by nchammas** [erikrose/blessings#99]
PyPI shows the latest release of blessings as [1.9.5](https://pypi.python.org/pypi/blessed). GitHub, on the other hand, shows [no such release](https://github.com/erikrose/blessings/releases) and only goes up to version 1.6, which was released in 2013.

Furthermore, it appears that the active branch of development is [blessings-integration](https://github.com/erikrose/blessings/tree/blessed-integration) and not master, which I found confusing.

Since the master branch is still the default branch for this project, I thought the project was not active when I first came upon it. The latest commit on master is from May 2014. It's not immediately obvious that one should look elsewhere for where the action is.

I'm not a pro by any means, but I think for most projects on GitHub the standard MO is to a) have all releases be tagged appropriately and b) have the active branch (if it is not master) be the default branch.

Is there any reason it's not like that for blessings too?

**Comment by nchammas** [comment]
Oh, hold on, I think I've confused blessings for blessed.

**Comment by jquast** [comment]
Hi @nchammas,

To be very clear, @erikrose authored blessings, which is at version 1.6. This matches the 'master' branch here on github of this very repository.

I authored a fork, 'blessed', which is at the version 1.9.5 you linked. This is on github as http://github.com/jquast/blessed

The master branch of each repository matches their latest pypi release, respectively.

I've only *very recently* been granted commit access here to blessings, so I'm working hard to merge all of the features and fixes of 'blessed' upstream, which is the purpose of the 'blessed-integration' branch.

So this is, in fact, where the action is.

(This is not the normal workflow of blessings, I suspect this is a one-off due to the great number of features added since last release requiring approval by @erikrose)

**Comment by nchammas** [comment]
@jquast Thanks for the quick response. I was just looking at your fork and wondering if that was a hard fork since this project seemed abandoned (given the release dates, commit activity, and so forth).

Sounds like that's not the case and the plan is to merge Blessed back into Blessings (via the blessed-integration branch), at which point master will be up-to-date and we'll get new releases here.

Sounds about right?

**Comment by jquast** [comment]
Yup, that's the plan sam.

The code is ready, I'm just finishing polishing and final review of the API docstrings, so pending @erikrose's final review, a new version of blessings should come out relatively soon.

In the meantime, if there are features in blessed that you want, you can just go ahead and use blessed.

I plan to blessed into a "stub" package that wraps blessings and ensures the previously defined API remains. The README will simply recommend to use blessings going forward, and all issues/enhancements will be transitioned.

**Comment by nchammas** [comment]
:+1:

**Comment by wimglenn** [comment]
Hi @jquast and @erikrose - could we have a status update on the blessings/blessed situation? It looks like both projects had releases in June of this year. Did the plan mentioned in Apr 2015 change?

**Comment by jquast** [comment]
I’m FOSS retired for a while, working extra full time for a while into the future at my day job, so from my end, it’s all open source, well tested, lots of great design ideas in the issues, and I’ll hand maintainership over to he first bright lad who wishes to do it.

We did attempt merges with earnest, time, and labor, at least twice before. I think Erik didn’t like some things, whether style or design, and neither of us could make the time to adjust it to his liking, but it’s certainly licensed to encourage it to be re-upped or merged, and I would gladly point to blessings if it enveloped it’s exact API, or, if I had more time, become a lightweight wrapper of any design differences. But I’ll tell you my FOSS time is limited to only a few beief GitHub comments per week, I’m sorry!

Best wishes to Erik!

**Comment by erikrose** [comment]
jquast is a terminal genius, of course. IIRC, what basically killed it was a really tangled git history we couldn't untangle. The blessed testing story is far superior, as it goes to great lengths to work around an ancient and pernicious setupterm-works-only-once-per-process bug in Python. I'm sure there are one or two blessings APIs I prefer, though I can't remember what they are. Both projects have moved on a bit since we tried and failed to merge. I just landed PR #135, for example. Blessed is more complicated and much bigger because it goes to great lengths to work on many exotic and ill-behaved platforms. Blessings remains, for now, a thin, simple wrapper around termcaps. Pick whichever sounds better, and you can always switch without too much trouble. Or, better yet, go clean up the merge PR, and we can put this to bed forever. :-)

**Comment by wimglenn** [comment]
All right - thanks for the info!
